# Generated by Django 4.2.3 on 2023-07-07 09:11

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('blogmain', '0002_blogpage_delete_homepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogsPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TestContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('firstName', models.CharField(default='firstName', help_text='Enter First Name', max_length=10, verbose_name='First Name')),
                ('lastName', models.CharField(default='lastName', help_text='Enter Last Name', max_length=10, verbose_name='Last Name')),
                ('approved', models.BooleanField(default=False)),
                ('page', modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='test_contents', to='blogmain.blogspage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='BlogPage',
        ),
    ]
