# Generated by Django 4.2.3 on 2023-07-08 09:56

from django.db import migrations
import wagtail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0005_blog_comment_delete_testcontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='content',
            field=wagtail.fields.RichTextField(max_length=2000, null=True),
        ),
    ]
