# Generated by Django 4.2.3 on 2023-07-18 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0007_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentPage',
            fields=[
                ('comment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blogmain.comment')),
            ],
            options={
                'abstract': False,
            },
            bases=('blogmain.comment',),
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='page',
        ),
    ]
