# Generated by Django 4.2.3 on 2023-07-22 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0008_commentpage_delete_subscriber_remove_comment_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='blog',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blogmain.blog'),
        ),
    ]
