# Generated by Django 4.2.3 on 2023-07-22 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0009_comment_blog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blog',
            new_name='blogID',
        ),
    ]
