# Generated by Django 4.2.3 on 2023-07-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0010_rename_blog_comment_blogid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='blogID',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blogmain.blog'),
        ),
    ]
