# Generated by Django 4.2.3 on 2023-07-22 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogmain', '0011_alter_comment_blogid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='blogID',
            new_name='blog',
        ),
    ]
